-- Create campaign table
DROP TABLE IF EXISTS CAMPAIGN;

CREATE TABLE CAMPAIGN (
	CF_ID FLOAT NOT NULL,
	CONTACT_ID INT NOT NULL,
	COMPANY_NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(250) NOT NULL,
	GOAL FLOAT NOT NULL,
	PLEDGED FLOAT NOT NULL,
	OUTCOME VARCHAR(50) NOT NULL,
	BACKERS_COUNT FLOAT NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	CURRENCY VARCHAR(50) NOT NULL,
	LAUNCH_DATE DATE,
	END_DATE DATE,
	CATEGORY_ID VARCHAR(50) NOT NULL,
	SUBCATEGORY_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (CF_ID),
	FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS (CONTACT_ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID),
	FOREIGN KEY (SUBCATEGORY_ID) REFERENCES SUBCATEGORY (SUBCATEGORY_ID)
);

-- Confirming import
SELECT
	*
FROM
	CAMPAIGN;

-- Create category table
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE CATEGORY (
	CATEGORY_ID VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	PRIMARY KEY (CATEGORY_ID)
);

-- Confirming import
SELECT
	*
FROM
	CATEGORY;

-- Create contacts table
DROP TABLE IF EXISTS CONTACTS;

CREATE TABLE CONTACTS (
	CONTACT_ID INT NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PRIMARY KEY (CONTACT_ID)
);

-- Confirming import
SELECT
	*
FROM
	CONTACTS;

-- Create subcategory table
DROP TABLE IF EXISTS SUBCATEGORY;

CREATE TABLE SUBCATEGORY (
	SUBCATEGORY_ID VARCHAR(50) NOT NULL,
	SUBCATEGORY VARCHAR(50) NOT NULL,
	PRIMARY KEY (SUBCATEGORY_ID)
);

-- Confirming import
SELECT
	*
FROM
	SUBCATEGORY;